[workspace]
resolver = "2"
members = [
    "crates/test_macros",
    "crates/trigonometry",
    "crates/benchmarks",
    "crates/arrow",
    "crates/array",
    "crates/cast",
    "crates/arithmetic"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
async-trait = "0.1.64"
tokio = { version = "1.22.0", features = ["macros", "rt-multi-thread"] }
wgpu = "0.15.1"
pollster = "0.3.0"
bytemuck = "1.13.0"
futures-intrusive = "0.5.0"
log =  { version =  "0.4.17" }